# Generated by Django 4.2.1 on 2026-02-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_autor_slug_editorial_slug_libro_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='slug',
            field=models.SlugField(blank=True, default='default', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='editorial',
            name='slug',
            field=models.SlugField(blank=True, default='default', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libro',
            name='slug',
            field=models.SlugField(blank=True, default='default', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
