# Generated by Django 4.2.1 on 2026-02-13 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogo', '0005_alter_comentario_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alquiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.now)),
                ('fecha_devolucion_prevista', models.DateField()),
                ('fecha_devolucion_real', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ALQUILADO', 'Alquilado'), ('DEVUELTO', 'Devuelto'), ('ATRASADO', 'Atrasado')], default='ALQUILADO', max_length=10)),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alquileres', to='catalogo.libro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alquileres', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
